name: XSpec-Tests
on: 
  - push
jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      SAXON_HOME: /tmp/saxon
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: install xspec
        run: git clone -b master https://github.com/xspec/xspec.git /tmp/xspec
      - name: install saxon
        run: |
          wget -O /tmp/saxon.zip https://github.com/Saxonica/Saxon-HE/releases/download/SaxonHE12-4/SaxonHE12-4J.zip
          mkdir -p $SAXON_HOME
          unzip /tmp/saxon.zip -d $SAXON_HOME

      - name: run tests
        run: /tmp/xspec/bin/xspec.sh -e tests/suite.xspec
